[project]
name = "jagex-account-creator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "drissionpage>=4.1.1.2",
    "imap-tools>=1.11.0",
    "loguru>=0.7.3",
    "pyotp>=2.9.0",
]
