[default]
headless = false
threads = 1
element_wait_timeout = 30
enable_dev_tools = false
cache_update_threshold = 0.3

[imap]
ip = "mail.domain.com"
port = 993
email = "catchall@domain.com"
password = "myCatchAllEmailPassword"

[account]
domains = ["mydomain1.com", "myotherdomain.net"]
password = "OsrsEnjoyer!123"
set_2fa = true

[proxies]
enabled = false
proxy_list = [
    # "ip:port:user:pass",
    # "ip:port:user:pass",
    # "ip:port:user:pass"
]
